codebender_compiler_status_check:
    pattern:  /status
    defaults: { _controller: CodebenderCompilerBundle:Default:status }

codebender_compiler_test:
    pattern:  /{authorizationKey}/test/
    defaults: { _controller: CodebenderCompilerBundle:Default:test }

codebender_compiler_homepage:
    pattern:  /{authorizationKey}/{version}
    defaults: { _controller: CodebenderCompilerBundle:Default:index }

codebender_compiler_delete_all:
    pattern:  /{authorizationKey}/{version}/delete/all/
    defaults: { _controller: CodebenderCompilerBundle:Default:deleteAllObjects }

codebender_compiler_delete_specific:
    pattern:  /{authorizationKey}/{version}/delete/{option}/{cachedObjectToDelete}
    defaults: { _controller: CodebenderCompilerBundle:Default:deleteSpecificObjects }

# redirecting the root
root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /status
        permanent: true
